package firstpackage;
// Generated 21-ene-2019 13:18:21 by Hibernate Tools 5.0.6.Final

/**
 * TAccesos generated by hbm2java
 */
public class TAccesos implements java.io.Serializable {

	private Integer codAcceso;
	private TEstaciones TEstaciones;
	private String descripcion;

	public TAccesos() {
	}

	public TAccesos(TEstaciones TEstaciones, String descripcion) {
		this.TEstaciones = TEstaciones;
		this.descripcion = descripcion;
	}

	public Integer getCodAcceso() {
		return this.codAcceso;
	}

	public void setCodAcceso(Integer codAcceso) {
		this.codAcceso = codAcceso;
	}

	public TEstaciones getTEstaciones() {
		return this.TEstaciones;
	}

	public void setTEstaciones(TEstaciones TEstaciones) {
		this.TEstaciones = TEstaciones;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

}
