package firstpackage;
// Generated 21-ene-2019 13:18:21 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TCocheras generated by hbm2java
 */
public class TCocheras implements java.io.Serializable {

	private Integer codCochera;
	private String nombre;
	private String direccion;
	private Set TTreneses = new HashSet(0);

	public TCocheras() {
	}

	public TCocheras(String nombre, String direccion) {
		this.nombre = nombre;
		this.direccion = direccion;
	}

	public TCocheras(String nombre, String direccion, Set TTreneses) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.TTreneses = TTreneses;
	}

	public Integer getCodCochera() {
		return this.codCochera;
	}

	public void setCodCochera(Integer codCochera) {
		this.codCochera = codCochera;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Set getTTreneses() {
		return this.TTreneses;
	}

	public void setTTreneses(Set TTreneses) {
		this.TTreneses = TTreneses;
	}

}
