package firstpackage;
// Generated 21-ene-2019 13:18:21 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TEstaciones generated by hbm2java
 */
public class TEstaciones implements java.io.Serializable {

	private Integer codEstacion;
	private String nombre;
	private String direccion;
	private int numaccesos;
	private int numlineas;
	private int numviajesdestino;
	private int numviajesprocedencia;
	private Set TViajesesForEstacionorigen = new HashSet(0);
	private Set TViajesesForEstaciondestino = new HashSet(0);
	private Set TLineaEstacions = new HashSet(0);
	private Set TAccesoses = new HashSet(0);

	public TEstaciones() {
	}

	public TEstaciones(String nombre, String direccion, int numaccesos, int numlineas, int numviajesdestino,
			int numviajesprocedencia) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.numaccesos = numaccesos;
		this.numlineas = numlineas;
		this.numviajesdestino = numviajesdestino;
		this.numviajesprocedencia = numviajesprocedencia;
	}

	public TEstaciones(String nombre, String direccion, int numaccesos, int numlineas, int numviajesdestino,
			int numviajesprocedencia, Set TViajesesForEstacionorigen, Set TViajesesForEstaciondestino,
			Set TLineaEstacions, Set TAccesoses) {
		this.nombre = nombre;
		this.direccion = direccion;
		this.numaccesos = numaccesos;
		this.numlineas = numlineas;
		this.numviajesdestino = numviajesdestino;
		this.numviajesprocedencia = numviajesprocedencia;
		this.TViajesesForEstacionorigen = TViajesesForEstacionorigen;
		this.TViajesesForEstaciondestino = TViajesesForEstaciondestino;
		this.TLineaEstacions = TLineaEstacions;
		this.TAccesoses = TAccesoses;
	}

	public Integer getCodEstacion() {
		return this.codEstacion;
	}

	public void setCodEstacion(Integer codEstacion) {
		this.codEstacion = codEstacion;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public int getNumaccesos() {
		return this.numaccesos;
	}

	public void setNumaccesos(int numaccesos) {
		this.numaccesos = numaccesos;
	}

	public int getNumlineas() {
		return this.numlineas;
	}

	public void setNumlineas(int numlineas) {
		this.numlineas = numlineas;
	}

	public int getNumviajesdestino() {
		return this.numviajesdestino;
	}

	public void setNumviajesdestino(int numviajesdestino) {
		this.numviajesdestino = numviajesdestino;
	}

	public int getNumviajesprocedencia() {
		return this.numviajesprocedencia;
	}

	public void setNumviajesprocedencia(int numviajesprocedencia) {
		this.numviajesprocedencia = numviajesprocedencia;
	}

	public Set getTViajesesForEstacionorigen() {
		return this.TViajesesForEstacionorigen;
	}

	public void setTViajesesForEstacionorigen(Set TViajesesForEstacionorigen) {
		this.TViajesesForEstacionorigen = TViajesesForEstacionorigen;
	}

	public Set getTViajesesForEstaciondestino() {
		return this.TViajesesForEstaciondestino;
	}

	public void setTViajesesForEstaciondestino(Set TViajesesForEstaciondestino) {
		this.TViajesesForEstaciondestino = TViajesesForEstaciondestino;
	}

	public Set getTLineaEstacions() {
		return this.TLineaEstacions;
	}

	public void setTLineaEstacions(Set TLineaEstacions) {
		this.TLineaEstacions = TLineaEstacions;
	}

	public Set getTAccesoses() {
		return this.TAccesoses;
	}

	public void setTAccesoses(Set TAccesoses) {
		this.TAccesoses = TAccesoses;
	}

}
