package firstpackage;
// Generated 21-ene-2019 13:18:21 by Hibernate Tools 5.0.6.Final

import java.util.HashSet;
import java.util.Set;

/**
 * TLineas generated by hbm2java
 */
public class TLineas implements java.io.Serializable {

	private Integer codLinea;
	private String nombre;
	private Set TLineaEstacions = new HashSet(0);
	private Set TTreneses = new HashSet(0);

	public TLineas() {
	}

	public TLineas(String nombre) {
		this.nombre = nombre;
	}

	public TLineas(String nombre, Set TLineaEstacions, Set TTreneses) {
		this.nombre = nombre;
		this.TLineaEstacions = TLineaEstacions;
		this.TTreneses = TTreneses;
	}

	public Integer getCodLinea() {
		return this.codLinea;
	}

	public void setCodLinea(Integer codLinea) {
		this.codLinea = codLinea;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getTLineaEstacions() {
		return this.TLineaEstacions;
	}

	public void setTLineaEstacions(Set TLineaEstacions) {
		this.TLineaEstacions = TLineaEstacions;
	}

	public Set getTTreneses() {
		return this.TTreneses;
	}

	public void setTTreneses(Set TTreneses) {
		this.TTreneses = TTreneses;
	}

}
