package firstpackage;
// Generated 21-ene-2019 13:18:21 by Hibernate Tools 5.0.6.Final

/**
 * TTrenes generated by hbm2java
 */
public class TTrenes implements java.io.Serializable {

	private Integer codTren;
	private TCocheras TCocheras;
	private TLineas TLineas;
	private String nombre;
	private String tipo;

	public TTrenes() {
	}

	public TTrenes(TCocheras TCocheras, TLineas TLineas, String nombre, String tipo) {
		this.TCocheras = TCocheras;
		this.TLineas = TLineas;
		this.nombre = nombre;
		this.tipo = tipo;
	}

	public Integer getCodTren() {
		return this.codTren;
	}

	public void setCodTren(Integer codTren) {
		this.codTren = codTren;
	}

	public TCocheras getTCocheras() {
		return this.TCocheras;
	}

	public void setTCocheras(TCocheras TCocheras) {
		this.TCocheras = TCocheras;
	}

	public TLineas getTLineas() {
		return this.TLineas;
	}

	public void setTLineas(TLineas TLineas) {
		this.TLineas = TLineas;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

}
